# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\syncing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SyncingProcessForm(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, SyncingProcessForm):
        SyncingProcessForm.setObjectName("SyncingProcessForm")
        SyncingProcessForm.resize(340, 150)
        SyncingProcessForm.setMinimumSize(QtCore.QSize(340, 150))
        SyncingProcessForm.setMaximumSize(QtCore.QSize(340, 150))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        SyncingProcessForm.setFont(font)
        self.label = QtWidgets.QLabel(SyncingProcessForm)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 61))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(SyncingProcessForm)
        self.progressBar.setGeometry(QtCore.QRect(20, 90, 301, 41))
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(SyncingProcessForm)
        self.pushButton.setGeometry(QtCore.QRect(260, 0, 81, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SyncingProcessForm)
        QtCore.QMetaObject.connectSlotsByName(SyncingProcessForm)

    def retranslateUi(self, SyncingProcessForm):
        _translate = QtCore.QCoreApplication.translate
        SyncingProcessForm.setWindowTitle(_translate("SyncingProcessForm", "同步中,请稍后"))
        self.label.setText(_translate("SyncingProcessForm", "同步中,请稍后"))
        self.pushButton.setText(_translate("SyncingProcessForm", "最小化"))
